name: 'Github Migrations Backup'
author: 'Skrepr'
description: 'Backup a Github Org with one Action'
inputs:
  GH_ORG:
    description: 'The GitHub org you want to make a backup for'
    required: true
  GH_APIKEY:
    description: 'The API token necessary to talk to the GitHub API'
    required: true
  GH_REPO:
    description: 'The GitHub repo you want to backup'
    required: true
  AZURE_CONTAINER_NAME:
    description: 'The Azure Container in which the archive will be stored'
    required: true
  AZURE_CONNECTION_STRING:
    description: 'The Connection String (including key) needed to complete authentication to Azure'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
