name: 'Github Migrations Backup'
author: 'Skrepr'
description: 'Backup a Github Org with one Action'
inputs:
  github-organization:
    description: 'The GitHub org you want to backup'
    required: true
  github-apikey:
    description: 'The API token necessary to talk to the GitHub API'
    required: true
  GH_REPO:
    description: 'The GitHub repo you want to backup'
    required: false
  azure-container-name:
    description: 'The Azure Container in which the archive will be stored'
    required: true
  azure-connection-string:
    description: 'The Connection String (including key) needed to complete authentication to Azure'
    required: true
  download-migration:
    description: 'Download the migration archive from GitHub'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
