# name: Backup repositories

# on:
#   schedule:
#     - cron: '0 1 * * 0'  # At 01:00 on Sunday

# jobs:
#   backup:
#     name: Create archive
#     runs-on: ubuntu-latest
#     timeout-minutes: 30

#     steps:
#     - name: Github Migrations Backup
#       uses: skrepr/github-backup-action@1.0.0
#       with:
#         github-organization: "your-organization-here"
#         github-apikey: ${}
#         aws-bucket-name: "your-bucket-here"
#         aws-bucket-region: "your-bucket-region-here"
#         aws-access-key: ${AWS_ACCESS_KEY} # Github Secret is advised
#         aws-secret-key: ${AWS_SECRET_KEY} # Github Secret is advised

#     # Save migration.data.id as an artifact at the end of the first run
#     - name: Archive Data
#       uses: actions/upload-artifact@v2
#       with:
#         name: migration-data
#         path: migration_response.json