name: Download archive

on:
  schedule:
    - cron: '0 3 * * 0'  # At 03:00 on Sunday

jobs:
  backup:
    name: Download archive
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    # Download the migration.data.id as an artifact at the beginning of the second run
    - name: Archive Data
      uses: actions/download-artifact@v2
      with:
        name: migration-data
        path: migration_response.json

    - name: Github Migrations Backup
      uses: skrepr/github-backup-action@1.0.0
      env:
        DOWNLOAD_MIGRATION: true
        AWS_BUCKET_NAME: "your-bucket-here"
        AWS_BUCKET_REGION: "your-bucket-region-here"
        AWS_ARN: "arn:aws:s3:::your-bucket-here"
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY} # Github Secret is advised
        AWS_SECRET_KEY: ${AWS_SECRET_KEY} # Github Secret is advised
