name: 'build-test'
on: # rebuild any PRs and main branch changes
  release:
    types: [published]
  push:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm run test

